server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://mariodingwaiwang.mysql.rds.aliyuncs.com:5999/spring_study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: edu
    password: eduPass_
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    default-property-inclusion: non_null
